In [1]:
#1
import numpy as np

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)

mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

Daniel Barte's Array: [19 65 34 17 58 41  6 31 42  8]
Mean: 32.1 Std Dev: 18.965494984312958


In [2]:
#2
import numpy as np

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)

row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Daniel Barte's Matrix:
 [[19  1 34 16]
 [17 29 19 34]
 [ 6 31 24  8]]
Row sums: [70 99 69]
Column sums: [42 61 77 58]


In [3]:
#3
import numpy as np

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)

slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)


Daniel Barte's 3D Array:
 [[[18  9  0]
  [ 1 15 16]
  [28 25 18]]

 [[ 1  8  5]
  [ 9 22 23]
  [27  7 10]]

 [[10 26  6]
  [10  2 28]
  [21 13 26]]]
Slice[:,1,:]:
 [[ 1 15 16]
 [ 9 22 23]
 [10  2 28]]


In [4]:
#4
import numpy as np

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Daniel Barte's Original: [19 65 34 17 58 41  6 31 42  8]
Filtered subset: []


In [5]:
#5
import numpy as np

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)

product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[19  1]
 [34 16]]
Matrix B:
 [[17 29]
 [19 34]]
A @ B:
 [[ 342  585]
 [ 882 1530]]
Determinant of A: 270.00000000000006


In [6]:
#6
import numpy as np

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Daniel Barte's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [7]:
#7
import numpy as np

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Daniel Barte's Modified 4x4 Array:
 [[ 0  1  0 16]
 [17 29 19 34]
 [ 0 31  0  8]
 [11 35 29 22]]


In [8]:
#8
import numpy as np

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)


Daniel Barte's Scores: [18 64 33 16 57 40  5 30 41  7]
Grades: ['Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail']


In [9]:
#9

import numpy as np
STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[19  1 34 16]
 [17 29 19 34]
 [ 6 31 24  8]]
Flattened: [19  1 34 16 17 29 19 34  6 31 24  8]
Transposed:
 [[19 17  6]
 [ 1 29 31]
 [34 19 24]
 [16 34  8]]


In [10]:
#10
import numpy as np

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[19  1 -1]
 [-1 17 29]
 [19 -1 -1]]


In [11]:
#11
import numpy as np
import pandas as pd

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'Score': np.random.randint(STUDENT_ID%50,
STUDENT_ID%100+50,5),
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
print(df)

           Name  Score  YearsCodePro
0  Daniel Barte     37            16
1  Daniel Barte     60            28
2  Daniel Barte     19            25
3  Daniel Barte     52            18
4  Daniel Barte     34             1


In [12]:
#12
import numpy as np
import pandas as pd

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'],
# Corrected to use a functional salary range, e.g., 40000 to 150000
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)


EdLevel
Bachelor     71325.5
Master      101505.0
PhD         117263.0
Name: ConvertedComp, dtype: float64


In [13]:
#13
import numpy as np
import pandas as pd

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Country': ['Philippines','USA','UK','Canada','Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)


       Country  ConvertedComp
2           UK         117263
4      Germany         106017
1          USA          96993
0  Philippines          74665
3       Canada          67986


In [14]:
#14
import numpy as np
import pandas as pd

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name':[STUDENT_NAME]*5,
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
high_exp = df[df['YearsCodePro']>STUDENT_ID%10]
print(high_exp)



           Name  YearsCodePro
0  Daniel Barte            18
4  Daniel Barte            15


In [15]:
#15
import numpy as np
import pandas as pd

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0          74665   50-100k
1          96993   50-100k
2         117263  100-150k
3          67986   50-100k
4         106017  100-150k


In [16]:
#16
import numpy as np
import pandas as pd

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
# Original Code Issue:
# np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)
# -> np.random.randint(12345, 12345, 5) which is a zero-length range.

# Corrected Code: Using a functional salary range (40000 to 150000)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})

df['LogComp'] = np.log(df['ConvertedComp'])
print(df)


   ConvertedComp    LogComp
0          74665  11.220767
1          96993  11.482394
2         117263  11.672175
3          67986  11.127057
4         106017  11.571355


In [17]:
#17
import numpy as np
import pandas as pd

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5),
'ConvertedComp': np.random.randint(40000, 150000, 5)
})

corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000      -0.981778
ConvertedComp     -0.981778       1.000000


In [18]:
#18
import numpy as np
import pandas as pd

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Calculate mean, median, and standard deviation for each 'EdLevel'
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index()
print(summary)

    EdLevel      mean    median          std
0  Bachelor   71325.5   71325.5  4722.766192
1    Master  101505.0  101505.0  6380.931593
2       PhD  117263.0  117263.0          NaN


In [19]:
#19
import numpy as np
import pandas as pd

STUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)

# Generate salaries: [100727, 136195, 130612, 100727, 95233]
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
threshold = 110000

# Create the 'HighPay' column using np.where()
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')
print(df)

   ConvertedComp HighPay
0          74665      No
1          96993      No
2         117263     Yes
3          67986      No
4         106017      No


In [20]:
#20
import numpy as np
import pandas as pd

TUDENT_NAME = "Daniel Barte"
STUDENT_ID = 250419

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
'Country': ['Philippines','USA','UK','Canada','Germany'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)

                 mean     max
Country                      
Canada        67986.0   67986
Germany      106017.0  106017
Philippines   74665.0   74665
UK           117263.0  117263
USA           96993.0   96993
