In [4]:
import numpy as np

# Step 2: Create a 1D array representing years of experience
years_exp = np.array([1, 3, 5, 7, 10, 67, 69])
print("Years of Experience:", years_exp)

# Step 3: Create a 2D array representing sample salaries (in thousands)
salaries = np.array([[50, 60, 70], [80, 90, 100],[101, 110, 115],[150, 160, 190]])
print("Salary Matrix:\n", salaries)

# Step 4: Create an array of zeros and ones for placeholder analysis
zeros_array = np.zeros((2, 2)) # 2x2 zeros
ones_array = np.ones((2, 3)) # 2x3 ones
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

identity_matrix = np.eye(3)
print("Identity Matrix (3x3):")
print(identity_matrix)

Years of Experience: [ 1  3  5  7 10 67 69]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]
 [101 110 115]
 [150 160 190]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5 # Add 5 years to all experience values
print("Years + 5:", exp_plus_5)

# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2 # Multiply all values by 2
print("Years * 2:", exp_times_2)

# Step 3: Dot product (simulate salary projections)
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

#Try it
exp_minus_2 = years_exp - 2
exp_div_2 = years_exp / 2
exp_values = np.exp(sample1) 
log_values = np.log(sample1)

print("-" * 30)
print("Subtraction (Years - 2):", exp_minus_2)
print("Division (Years / 2):", exp_div_2)
print("Exponential (e^x on [1,2,3]):", exp_values)
print("Natural Log (ln on [1,2,3]):", log_values)

Years + 5: [ 6  8 10 12 15 72 74]
Years * 2: [  2   6  10  14  20 134 138]
Dot Product: 32
------------------------------
Subtraction (Years - 2): [-1  1  3  5  8 65 67]
Division (Years / 2): [ 0.5  1.5  2.5  3.5  5.  33.5 34.5]
Exponential (e^x on [1,2,3]): [ 2.71828183  7.3890561  20.08553692]
Natural Log (ln on [1,2,3]): [0.         0.69314718 1.09861229]


In [10]:
# Step 1: Access individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays
print("First two salaries:", salaries[0, :2]) # First two elements of first row

# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])

#Try it
reversed_years = years_exp[::-1]
print("\nReversed years_exp:", reversed_years)

salary_subgroup = salaries[0:2, 1:3]
print("Subgroup of salaries (2x2 slice):\n", salary_subgroup)

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [ 60  90 110 160]
Last year of experience: 69

Reversed years_exp: [69 67 10  7  5  3  1]
Subgroup of salaries (2x2 slice):
 [[ 60  70]
 [ 90 100]]


In [11]:
# Step 1: Reshape 1D array into 2x3 matrix for batch analysis
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

# Step 3: Transpose example
print("Transposed Array:\n", reshaped_exp.T)

#Try it
try_it_3x2 = reshaped_exp.reshape(3, 2)
try_it_column = reshaped_exp.reshape(6, 1)

print("-" * 30)
print("Try It - 3x2 Reshape:\n", try_it_3x2)
print("\nTry It - 6x1 (Column Vector):\n", try_it_column)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]
------------------------------
Try It - 3x2 Reshape:
 [[1 2]
 [3 4]
 [5 6]]

Try It - 6x1 (Column Vector):
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [12]:
# Step 1: Add a bonus array to salaries using broadcasting
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus # Adds corresponding bonus to each column
print("Salaries after bonus:\n", salaries_with_bonus)

#Try it
scaling_factor = 1.1
scaled_salaries = salaries * scaling_factor

print("-" * 30)
print("Scaled Salaries (10% Raise):\n", scaled_salaries)

Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]
 [106 120 130]
 [155 170 205]]
------------------------------
Scaled Salaries (10% Raise):
 [[ 55.   66.   77. ]
 [ 88.   99.  110. ]
 [111.1 121.  126.5]
 [165.  176.  209. ]]


In [13]:
# Step 1: Mean of years of experience
print("Mean experience:", np.mean(years_exp))

# Step 2: Standard deviation of experience
print("Std deviation of experience:", np.std(years_exp))

# Step 3: Max and Min salaries
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))

# Step 4: Sum of salaries
print("Sum of all salaries:", np.sum(salaries))

#Try it
median_exp = np.median(years_exp)
percentile_25 = np.percentile(salaries, 25)
percentile_75 = np.percentile(salaries, 75)

print("-" * 30)
print("Median experience:", median_exp)
print("25th Percentile of Salaries:", percentile_25)
print("75th Percentile of Salaries:", percentile_75)

Mean experience: 23.142857142857142
Std deviation of experience: 28.49776217494265
Max salary: 190 Min salary: 50
Sum of all salaries: 1276
------------------------------
Median experience: 7.0
25th Percentile of Salaries: 77.5
75th Percentile of Salaries: 123.75


In [14]:
# Step 1: Apply trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

# Step 2: Apply function along rows (sum salaries per person)
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

#Try it
sqrt_salaries = np.sqrt(salaries)
log_salaries = np.log10(salaries)

def add_tax(row):
     return row * 0.95  # Returns 95% of the original salary

taxed_salaries = np.apply_along_axis(add_tax, 1, salaries)

print("-" * 30)
print("Square Root of Salaries:\n", sqrt_salaries)
print("\nSalaries after 5% Tax (Custom Function):\n", taxed_salaries)

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270 326 500]
------------------------------
Square Root of Salaries:
 [[ 7.07106781  7.74596669  8.36660027]
 [ 8.94427191  9.48683298 10.        ]
 [10.04987562 10.48808848 10.72380529]
 [12.24744871 12.64911064 13.78404875]]

Salaries after 5% Tax (Custom Function):
 [[ 47.5   57.    66.5 ]
 [ 76.    85.5   95.  ]
 [ 95.95 104.5  109.25]
 [142.5  152.   180.5 ]]


In [15]:
import pandas as pd

# Step 1: Create a NumPy array of random data
data = np.random.randint(1, 50, size=(5, 3))

# Step 2: Convert the array into a DataFrame
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

# Step 3: Apply NumPy functions to DataFrame columns
df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)

# Step 4: Analyze data using Pandas correlation
print("Correlation Matrix:\n", df_data.corr())

#Try it
column_means = np.mean(df_data, axis=0)
column_medians = np.median(df_data, axis=0)

df_data['Square_Z'] = np.square(df_data['Z'])
df_data['Exp_X_Small'] = np.exp(df_data['X'] / 10)

print("-" * 30)
print("Column Means:\n", column_means)
print("\nColumn Medians:\n", column_medians)
print("\nFinal DataFrame with Square and Exp:\n", df_data)

Generated Data:
     X   Y   Z
0  26  26  31
1  35   7  16
2  37  18  11
3  29  37  19
4  42   9  13
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  26  26  31  3.258097  5.099020
1  35   7  16  3.555348  2.645751
2  37  18  11  3.610918  4.242641
3  29  37  19  3.367296  6.082763
4  42   9  13  3.737670  3.000000
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000 -0.759024 -0.856003  0.997685 -0.755456
Y      -0.759024  1.000000  0.485640 -0.758589  0.994110
Z      -0.856003  0.485640  1.000000 -0.884127  0.495992
Log_X   0.997685 -0.758589 -0.884127  1.000000 -0.757320
Sqrt_Y -0.755456  0.994110  0.495992 -0.757320  1.000000
------------------------------
Column Means:
 X         33.800000
Y         19.400000
Z         18.000000
Log_X      3.505866
Sqrt_Y     4.214035
dtype: float64

Column Medians:
 [35.         18.         16.          3.55534806  4.24264069]

Final DataFrame with Square and Exp:
     X   Y   Z

In [16]:
# Step 1: Save the DataFrame to a CSV file
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

# Step 2: Load the CSV file back into a new DataFrame
df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported)

# Step 3: Generate summary statistics
summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)

# Step 4: Display column means and standard deviations
print("Column Means:\n", df_imported.mean())
print("Column Standard Deviations:\n", df_imported.std())

#Try it
print("\n--- Section 9 Try It ---")
df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y']
df_imported.to_csv('modified_data.csv', index=False)
print("Modified data saved to 'modified_data.csv'.")
print("New Column 'Sum_XY' Preview:\n", df_imported[['X', 'Y', 'Sum_XY']].head())


Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y  Square_Z  Exp_X_Small
0  26  26  31  3.258097  5.099020       961    13.463738
1  35   7  16  3.555348  2.645751       256    33.115452
2  37  18  11  3.610918  4.242641       121    40.447304
3  29  37  19  3.367296  6.082763       361    18.174145
4  42   9  13  3.737670  3.000000       169    66.686331
Summary Statistics:
                X          Y          Z     Log_X    Sqrt_Y    Square_Z  \
count   5.000000   5.000000   5.000000  5.000000  5.000000    5.000000   
mean   33.800000  19.400000  18.000000  3.505866  4.214035  373.600000   
std     6.379655  12.421755   7.874008  0.192229  1.432616  340.842779   
min    26.000000   7.000000  11.000000  3.258097  2.645751  121.000000   
25%    29.000000   9.000000  13.000000  3.367296  3.000000  169.000000   
50%    35.000000  18.000000  16.000000  3.555348  4.242641  256.000000   
75%    37.000000  26.000000  19.000000  3.610918  5.099020  361.0

In [18]:
import pandas as pd
import numpy as np

# Step 1: Load the dataset with a safety check
try:
    df_kaggle = pd.read_csv('survey_results_public.csv')
    print("Stack Overflow Survey loaded successfully.")
except FileNotFoundError:
    df_kaggle = pd.read_csv('sample_data.csv')
    print("Survey file not found. Using sample_data.csv as a placeholder.")

# Step 2: Select relevant columns safely
# We check if 'Country' exists; if not, we use columns from your sample_data.csv
if 'Country' in df_kaggle.columns:
    target_cols = ['Country', 'EdLevel', 'YearsCodePro', 'ConvertedComp']
else:
    target_cols = ['X', 'Y', 'Z'] # Fallback for your current sample_data.csv

df_subset = df_kaggle[target_cols]

# Step 3: Clean the data
df_clean = df_subset.dropna().copy()

# Step 4: Categorize experience into groups
# If working with the real survey, we categorize by years
if 'YearsCodePro' in df_clean.columns:
    df_clean['YearsCodePro'] = pd.to_numeric(df_clean['YearsCodePro'], errors='coerce')
    df_clean = df_clean.dropna()
    df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')
else:
    # Placeholder logic for sample_data (X represents years)
    df_clean['ExperienceLevel'] = np.where(df_clean['X'] >= 25, 'Senior', 'Junior')

# Step 5 & 6: Group and Reset Index
group_by_col = 'Country' if 'Country' in df_clean.columns else 'Z'
value_col = 'ConvertedComp' if 'ConvertedComp' in df_clean.columns else 'Y'

grouped_data = df_clean.groupby([group_by_col, 'ExperienceLevel'])[value_col].mean().reset_index()
print("\nFormatted Grouped Data:\n", grouped_data.head())

# --- "Try It" Section ---

# 1. Change grouping to EdLevel and compute Median/Std
if 'EdLevel' in df_clean.columns:
    ed_stats = df_clean.groupby('EdLevel')['ConvertedComp'].agg(['median', 'std']).reset_index()
    print("\nEducation Stats (Median & Std):\n", ed_stats)

# 2. Explore top 10 countries with highest average compensation
if 'Country' in df_clean.columns:
    top_10 = grouped_data.groupby('Country')[value_col].mean().sort_values(ascending=False).head(10)
    print("\nTop 10 Highest Paying Countries:\n", top_10)

Survey file not found. Using sample_data.csv as a placeholder.

Formatted Grouped Data:
     Z ExperienceLevel     Y
0  11          Senior  18.0
1  13          Senior   9.0
2  16          Senior   7.0
3  19          Senior  37.0
4  31          Senior  26.0
